### ISSUE TITLE
Version 3.3.2 not working on local server 

### ISSUE THREAD

**Issue by KonstantinFromRussia** [redaxscript/redaxscript#582]
Hello!
I already spoke with you last year about launching your system on a local server under the operating system Windows.
In the version of your cms 3.3.2 - the same problem.
When running on a local server - a white screen, nothing happens.
CMS version 3.2.3 - runs fine.

**Comment by redaxmedia** [comment]
Hello Konstantin - you have multiple options:

1. Give 4.0.0 Alpha* a try
1. Just stick to version 3.2.3 until 4.0.0 is stable
1. Enable `error_reporting(-1)` and report the output here

_(*)  be aware that looooot of things changed - so this is not a quick win if you need to migrate a website, template or even both - if not you can benefit from the brand new dev server that makes your local server obsolete - read more via [README.md](https://github.com/redaxscript/redaxscript#installation)_

**Comment by KonstantinFromRussia** [comment]
I apologize, did not notice that the new versions of the script only work on PHP 7.2
For free and cheap hosting is not exactly good. (IMHO)

Under PHP 7.2  script version 3.3.2 - perfectly working.
Version 4.0 is not.

**Comment by redaxmedia** [comment]
Hey...
can I help you out and buy some hosting? 😂
I do not plan to continue the development of 3.x.x in the future. So give me the error reporting please.
Henry


Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Konstantin from Russia <notifications@github.com> Datum: 07.10.18  18:45  (GMT+01:00) An: redaxscript/redaxscript <redaxscript@noreply.github.com> Cc: Henry Ruhs <info@redaxmedia.com>, Comment <comment@noreply.github.com> Betreff: Re: [redaxscript/redaxscript] Version 3.3.2 not working on local server  (#582) 
I apologize, did not notice that the new versions of the script only work on PHP 7.2

For free and cheap hosting is not exactly good. (IMHO)
Under PHP 7.2  script version 3.3.2 - perfectly working.

Version 4.0 is not.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/redaxscript/redaxscript","title":"redaxscript/redaxscript","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/redaxscript/redaxscript"}},"updates":{"snippets":[{"icon":"PERSON","message":"@KonstantinFromRussia in #582: I apologize, did not notice that the new versions of the script only work on PHP 7.2\r\nFor free and cheap hosting is not exactly good. (IMHO)\r\n\r\nUnder PHP 7.2  script version 3.3.2 - perfectly working.\r\nVersion 4.0 is not."}],"action":{"name":"View Issue","url":"https://github.com/redaxscript/redaxscript/issues/582#issuecomment-427667651"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/redaxscript/redaxscript/issues/582#issuecomment-427667651",
"url": "https://github.com/redaxscript/redaxscript/issues/582#issuecomment-427667651",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [redaxscript/redaxscript] Version 3.3.2 not working on local server  (#582)",
"sections": [
{
"text": "",
"activityTitle": "**Konstantin from Russia**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@KonstantinFromRussia",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"redaxscript/redaxscript\",\n\"issueId\": 582,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"redaxscript/redaxscript\",\n\"issueId\": 582\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/redaxscript/redaxscript/issues/582#issuecomment-427667651"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 388791564\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by KonstantinFromRussia** [comment]
Thank you. It's not about the money, it's just IMHO :)

**Comment by redaxmedia** [comment]
Try 4.0.0 on your local PC... it would be very cool to have some feedback


Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Konstantin from Russia <notifications@github.com> Datum: 07.10.18  19:44  (GMT+01:00) An: redaxscript/redaxscript <redaxscript@noreply.github.com> Cc: Henry Ruhs <info@redaxmedia.com>, Comment <comment@noreply.github.com> Betreff: Re: [redaxscript/redaxscript] Version 3.3.2 not working on local server  (#582) 
Thank you. It's not about the money, it's just IMHO :)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/redaxscript/redaxscript","title":"redaxscript/redaxscript","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/redaxscript/redaxscript"}},"updates":{"snippets":[{"icon":"PERSON","message":"@KonstantinFromRussia in #582: Thank you. It's not about the money, it's just IMHO :)"}],"action":{"name":"View Issue","url":"https://github.com/redaxscript/redaxscript/issues/582#issuecomment-427672132"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/redaxscript/redaxscript/issues/582#issuecomment-427672132",
"url": "https://github.com/redaxscript/redaxscript/issues/582#issuecomment-427672132",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [redaxscript/redaxscript] Version 3.3.2 not working on local server  (#582)",
"sections": [
{
"text": "",
"activityTitle": "**Konstantin from Russia**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@KonstantinFromRussia",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"redaxscript/redaxscript\",\n\"issueId\": 582,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"redaxscript/redaxscript\",\n\"issueId\": 582\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/redaxscript/redaxscript/issues/582#issuecomment-427672132"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 388791564\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by KonstantinFromRussia** [comment]
Ok.
My php.ini version 7.2
```
error_reporting = E_ALL
display_errors = On
display_startup_errors = On
log_errors = On
```
version 3.3.2 - perfectly working
version on github - not working
At start - the white screen. no error messages. Logs are empty.

**Comment by redaxmedia** [comment]
Try `grunt server --debug-mode`

**Comment by KonstantinFromRussia** [comment]
Here I can not help, sorry.
I have a local server under Windows

**Comment by redaxmedia** [comment]
You don't need a local server like XAMPP or WAMP as `grunt serve` is started a the internal PHP web-server :-)

**Comment by redaxmedia** [comment]
I just can repeat myself that you don't need something like that to run latest Redaxscript. You can wait for the final and packed version from the website and do it the old fashion way. Closing this issue for now.

**Comment by redaxmedia** [comment]
I created a collection of PowerShell routines to help Windows developers installing all the software they need for Redaxscript: https://github.com/redaxscript/redaxscript-powershell
