### ISSUE TITLE
Community module

### ISSUE THREAD

**Issue by lagkdok** [redaxscript/redaxscript#662]
hi,
when i tried the script i didn't find any option about sending private message or email between users so please, is it possible to add it?
anthor request, it possible to add sub groups for users?
thank you so much.

**Comment by redaxmedia** [comment]
@lagkdok Messaging between users is possible by creating a module. Sub groups are not possible and I not gonna plan to support this in the future.

If you know how to program PHP and open to join development, then I can create you a skeleton module you can work on. Otherwise I would move this to the backlog as I really like the idea.

**Comment by redaxmedia** [comment]
I close this as there was no response and without some help this not gonna happen.
