### ISSUE TITLE
Installer failed to load Dist path

### ISSUE THREAD

**Issue by bilel** [redaxscript/redaxscript#698]
After following the suggested installation method using git and composer, I noticed that the installer requires many js scripts from a Dist folder which never exist. 
I replaced the path by Assets to do the trick !
Sometimes it's looking for a minified version that is also unavailable...

Then after the installation, the same issue would happen where many modules call for unavailable js scripts .

Is it a different repo or I'm I missing a step to pre-compile the project?

Thank you

**Comment by redaxmedia** [comment]
Hey,

thanks for reaching out to me.

It sounds like babel.js failed to generate `dist/scripts` while booting up the application using `npm start` or `grunt serve` right before the internal development server is started? Are you running your own webserver? If so then use `npm run build` to generate all the dist folders.

Please report your operation system and node.js version if your issue is not solved.

**Comment by bilel** [comment]
Yes it seems I had to check all projects pre-compiler dependencies first ! So After running :

- npm install
- npm run build

Everything went fine ! 
Thank you

**Comment by redaxmedia** [comment]
Great... reach out for more question any time soon and consider to give us a star on GitHub.
